# Generated by Django 4.0.2 on 2022-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_data_time_transaction_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
