# Generated by Django 4.0.2 on 2022-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='points_method',
            field=models.CharField(blank=True, choices=[('SignUp Bonus', 'SignUp Bonus'), ('Referral Bonus', 'Referral Bonus'), ('Events Points', 'Events Points')], max_length=255, null=True),
        ),
    ]
